blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Simen Docs 
    url: https://case.simen.ai/en/welcome
    about: Please ask and answer questions here.
  - name: ğŸŒ Simen Website 
    url: https://simen.ai
    about: Please ask and answer questions here.
  - name: ğŸ“§ Support Team
    url: mailto:hi@simen.ai
    about: For account and billing questions. 